version: 0.2

phases:
  install:
    commands:
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build